### ISSUE TITLE
Part list

### ISSUE THREAD

**Issue by pc1oad1etter** [Nephiel/sdlocker-tiny#2]
Could you give a complete list of parts for this project?  Looks really great.

**Comment by pc1oad1etter** [comment]
Here's my stab at it.  What am I missing?  
What I am pulling out of your documentation:
- ATTINY85
- LM3940
- 300 Resistor x2
- 1 button (?)
- 1 LED (?)
- SD Card socket

From LM3940 Spec:
- 47 uF Capacitor
- 33 uF Low ESR Capacitor

**Comment by Nephiel** [comment]
The capacitors are 0.47μF (not 47μF) and 33μF. The first one is not strictly needed if you place the 33μF one close to the LM3940. For the second one, any 33μF low ESR electrolytic capacitor should work.

You'll also need a female microUSB socket for the AC adapter.
