### ISSUE TITLE
wish to purchase

### ISSUE THREAD

**Issue by RHelmuth** [Nephiel/sdlocker-tiny#3]
@Nephiel 
I would like to know whether you'd consider selling a unit to me? See my comment here: https://hackaday.com/2014/01/18/the-tiniest-sd-card-locker/#comment-5030677

You can contact me by mailing to reuben [dot] register [at] icloud [dot] com

Thanks!
Reuben

**Comment by Nephiel** [comment]
I'm afraid right now I do not have the time or resources to do it. Sorry!

**Comment by CRImier** [comment]
@Nephiel I can try making some PCBs and selling these myself on Tindie, would you mind? Will add a disclaimer like "software comes as-is, please do not bug the author" disclaimer, if desired. Got most of the components already, just need to draw&order PCBs and get some SD card slots.

**Comment by Nephiel** [comment]
@CRImier Sure, feel free to do so. You can fork this repo and link to your fork instead.

**Comment by CRImier** [comment]
Indeed, sounds like a better idea. Thank you!

**Comment by RHelmuth** [comment]
Would it take a lot of effort to add the option to permanently lock (e.g. by holding the button for 3-5 seconds)? I think having both options would make it so much more attractive and would broaden your target customer base.

**Comment by CRImier** [comment]
I will look into the code - it might very well be a simple change.

**Comment by RHelmuth** [comment]
@CRImier, the other thing you should be thinking about is supporting SDXC cards. Perhaps they already work, but I did notice they weren't listed where the types were being defined (lines 105-107). With SDXC cards becoming more common-place, it would be good to support them.

**Comment by CRImier** [comment]
I don't have any SDXC cards so I won't be able to test it, and I think it's not a worthwhile investment for now (given that testing will result in broken cards). Feel free to [open an issue](https://github.com/CRImier/sdlocker-tiny/issues/new) in my repo, though, so that whoever's interested could chime in and see if something can be done.

**Comment by RHelmuth** [comment]
Hey! Just checking in to see how you’ve come along with building these. Any progress? Any need for a tester?! ;-)

Reuben

**Comment by CRImier** [comment]
Designed and ordered PCBs, will arrive to me in a week, then I'll assemble one, flash it, test it and let you know =)

**Comment by RHelmuth** [comment]
Perfect! Do you have a price in mind for selling these?

**Comment by CRImier** [comment]
![dscn6215](https://user-images.githubusercontent.com/3173633/48982834-5c877a80-f0f0-11e8-9495-58947691d1b9.JPG)
Assembled boards, will test the next week and see.

**Comment by RHelmuth** [comment]
Super! I’m getting anxious. :-)

**Comment by RHelmuth** [comment]
Any update? Are they working?!
Do you have CashApp or PayPal?
~Reuben

**Comment by RHelmuth** [comment]
@CRImier  Have you been able to test these? I’m getting ready to place my order of SD cards but want to be sure that our distribution plan will work before I do so.
Thanks!

**Comment by CRImier** [comment]
Lost the device for a while (and didn't have any more ATTiny sockets for testing so couldn't assemble any more), now found it, flashed it, found two sacrificial SD cards and tested it. The PCB's going to need a few jumper wires, but nothing major. How many do you need? Do you need them set to TMP or to PERM? Both seem to work - TMP locking works on and off, PERM works on and doesn't turn off (which is kind of the point =D ). I can assemble one or two more additionally to what I have. Price is $10, shipping is $5 to USA, $4 to EU (regardless of QTY), can send out Monday morning.

**Comment by RHelmuth** [comment]
@CRImier, is it possible to do both TMP and PERM with the same device (e.g. holding the button for ≥5 seconds would flip the PERM bit)? 
Please email me directly (reubedu [at] gmail [dot] com) so we can exchange payment and shipping information.
Thanks!

**Comment by k-tronik** [comment]
Please may I put my name here in the hope when this project is ready, to be contacted...also would be interested in this working with SDXC, happy to buy and test....re-flash and re-test....with my SDXC cards...I can flash Attiny stuff.... ;)

**Comment by CRImier** [comment]
@RHelmuth I've implemented the PERM flashing - you need to hold the button during the card insertion, the LED will flash a pattern and switch into PERM flashing mode. Code's posted over at my repo. Let me know that's OK with you and we can talk about payment/shipping. Will try implementing the "hold to PERM thing" this weekend, sounds more convenient

@k-tronik I don't have any SDXC cards and don't like to write the code blindly without testing, however, if you're OK with writing the code yourself, I'd be happy to sell you the hardware (with a testing-friendly socket pictured above).

**Comment by k-tronik** [comment]
opps...I needed 'U3 SDHC'..my bad... not SDXC, its just bigger size...not faster... so when ready I will order 2 units please.... K

**Comment by k-tronik** [comment]
@CRImier opps...I needed 'U3 SDHC'..my bad... not SDXC, its just bigger size...not faster... so when ready I will order 2 units please.... K

**Comment by CRImier** [comment]
Okay, good!There's no need to flash ATTinys then, I'll just make two more units without testing-friendly sockets, pre-flashed.

**Comment by k-tronik** [comment]
@CRImier Ok thx again...I will make up the 3D printed cases....and post design to thingiverse once you have more boards made up....thx again for this!

**Comment by RHelmuth** [comment]
@CRImier the "hold during insertion" is an acceptable implementation for me, thanks! It may be less 'intuitive', but on the other hand, one is less likely to **accidentally** do a PERM lock so it may even be preferable.

**Comment by CRImier** [comment]
@k-tronik will throw a .STEP model in your direction sometime soon, then.

@RHelmuth preventing accidents was the intention, indeed - that's the version I personally will be using. Question, though - what's your workflow? Will you be setting cards to PERM en masse, or just occasionally? If you have a batch of cards you need to flash, the "hold to PERM" workflow might just work better.

**Comment by RHelmuth** [comment]
For now PERM will be an occasional use and we’ll be using TEMP a LOT. 

THANKS 
Reuben

**Comment by CRImier** [comment]
Ah okay, then the current code will be very suitable =)

**Comment by CRImier** [comment]
@k-tronik here's a colored .STEP model of the board with all the components:

[sd_locker.zip](https://github.com/Nephiel/sdlocker-tiny/files/2683289/sd_locker.zip)

![image](https://user-images.githubusercontent.com/3173633/50050559-38bfbf00-0107-11e9-8df7-b2d78690a4c3.png)

**Comment by k-tronik** [comment]
@CRImier WOW, nice...please can you export that file as a STL file...not to print...just to drop in to my workflow of tinkercad.... thx again  K

**Comment by CRImier** [comment]
@k-tronik here you go

[sd_locker.stl.zip](https://github.com/Nephiel/sdlocker-tiny/files/2683306/sd_locker.stl.zip)

![image](https://user-images.githubusercontent.com/3173633/50050777-abcc3400-010d-11e9-8e81-deda2b9c0d2b.png)

**Comment by k-tronik** [comment]
@CRImier thx again....so USB for input power...any idea of power drain in use, maybe do a battery case, version a well....

**Comment by CRImier** [comment]
@k-tronik The power consumption seems to be negligible - <10mA at 5V or so. Should be possible to make a separate battery-powered version, but I'm not sure it's worth the effort - I'd sell it for about $20-$25, and I'm not sure people would be interested in that. I can mod the existing PCBs manually for you - I'm now sketching the Tindie page, will consider adding a +$10 option to "make it battery-powered", with a charger added and a slightly different regulator (more efficient). You'll need to bring your own battery - something like 3.7V/200-400mAh will work, shouldn't set you back more than a couple of dollars.

**Comment by k-tronik** [comment]
@CRImier so I will just add a  coin cell at the bottom...if needed...did a quick case mock up...just need to get graphic for top and add any logos you need...
![3d design sd_loker](https://user-images.githubusercontent.com/45860766/50051040-6e43c700-015e-11e9-8a8c-b8221609ffaf.png)

**Comment by CRImier** [comment]
Nice case! However, you don't have the opening for a button. A coin cell will work until a certain point (2.7V I believe), but it should be OK - there are two pins to add one, thankfully. Didn't think of a coin cell, now that you've said it, I realise it's a very clever and really simple solution!

**Comment by k-tronik** [comment]
@CRImier will also need to sort out the button for the cased version....one idea is add 2x thru hole pads behind switch for panel mount switch on case...and do same for LED....you could then sell cased version for more...

**Comment by CRImier** [comment]
I can't do anything about the button now, and probably not until the next year. Can't you add a small hinge on the top cover for pressing the button? I'm not sure I will be doing too many revisions of this (since each revision is a time&money investment that might not pay off fully), and you can already solder wires to the switch and LED pins if needed. "Sell for more" - I sure can put a larger price on it, but I'm not sure people will buy it (esp. given the difference's not that big).

**Comment by CRImier** [comment]
If you screenshot your design file for the top part of the case (from the inside, specifically), I can show how the hinge would look like.

**Comment by k-tronik** [comment]
I would not open the case...to push a button...I would just push on your button via a rod and printed hole...or add another case mounted switch for my unit...what ever the case...you correct...get you $$ back for this version before you move on....I hear ya!!! we will just work with what we have....and make a few cases for it....if you like send me some logos or image to go on the box...happy to help out....K

**Comment by CRImier** [comment]
Can add my GitHub avatar and "CRImier" somewhere =) Here's an SVG (vector) image: [crimier_avatar.zip](https://github.com/Nephiel/sdlocker-tiny/files/2683350/crimier_avatar.zip) Don't forget to refer to yourself, too - the case looks great!

**Comment by CRImier** [comment]
also, not "open the case" - you can add a small hinge like this:

![image](https://user-images.githubusercontent.com/3173633/50051378-60b81e00-0119-11e9-8299-794a92df3743.png)

**Comment by k-tronik** [comment]
OK, I get ya now...I will do that....:) all final tweeking will be done with PCBs in hand.... :)

**Comment by k-tronik** [comment]
![sd_lockerwip](https://user-images.githubusercontent.com/45860766/50051513-cf23cd00-0167-11e9-9fe8-96d992e7ee2c.png)

looking better.....logos on the bottom maybe....K

**Comment by k-tronik** [comment]
> Nice case! However, you don't have the opening for a button. A coin cell will work until a certain point (2.7V I believe), but it should be OK - there are two pins to add one, thankfully. Didn't think of a coin cell, now that you've said it, I realise it's a very clever and really simple solution!

 lets set B.O.D @ 2.7v for now on Attiny85.... **assuming no issues to run on 2.7v**  will add ON/ OFF switch and a battery of some sort...given the 10mA peak....coin cell might be a but under done..but happy to play around...

**Comment by CRImier** [comment]
SD cards run down to 2.7V (like the CR2032 and similar batteries), even though 3.3V is the usual operational voltage - I can check if it actually functions down to 2.6V or so tomorrow or the day after. As for BOD, will check, I think it's already set at 2.7V in my setup. ON/OFF switch shouldn't be necessary, as the SD card insertion switch controls the power (the device's not powered until the card is inserted). I will see, might be able to make a ready-to-go battery-powered setup for you.

**Comment by RHelmuth** [comment]
@k-tronik and @CRImier how about having the basic instructions printed on the case (either on the case bottom if space allows, or even on the inside of the lid)? I envision something like this:
![image](https://user-images.githubusercontent.com/32963005/50057224-b4515880-0167-11e9-8edf-9eb86115c966.png)

**Comment by CRImier** [comment]
That's very cool, but I don't think it will easily be 3D-printable. I'm going to have instructions on my Tindie page:
```
###How does it work?
- Plug in the USB (used for power)
- Plug in the SD card - the device will power up
- LED lights on boot for a couple of seconds, then shows the card's lock status (not lit = unlocked, lit = locked)
- Press the button to toggle the card's lock state
- By default, the TMP lock bit is toggled - it allows to unlock the card.
- To toggle the PERM bit (and make the card permanently read-only), hold the button while plugging the SD card in - it will flash the SOS pattern on the LED (and won't proceed until you release the button). This is done so you don't toggle the PERM bit by accident.
```
Plus, I'm going to make a video on using it. Just need to make some photos for the Tindie page, then 1 or 2 days and it will be orderable by @k-tronik =) As for @RHelmuth's board, will email you now.

**Comment by CRImier** [comment]
@k-tronik BTW, are your case files available? We're now arranging the PCB shipment with RHelmuth, and I was wondering - if you could share the Tinkercad project files, I would be able to printing two of those to add to the shipment, adjusting the source if necessary. My email I use with Tinkercad is crimier@yandex.ru .

**Comment by k-tronik** [comment]
@CRImier its just mock up...case will close on my printer...but maybe not yours...its not finished...and you would have to stuff around to make it so...I can get stuff world wide for a few $$ thru the post...once I get boards, I will get it done....and send part from here....or you can take what I have...and stuff around...your call....but it won't go on thingiverse till is finished and tested,......K

**Comment by CRImier** [comment]
@k-tronik if you can get the source files to me, I can tweak them, no worries - then share my results, of course.

**Comment by CRImier** [comment]
@k-tronik let me know if you have time to share the files. I'll be looking at creating my own quick&dirty prototype, in the meantime =)

**Comment by k-tronik** [comment]
Hey sorry about delay....tinkercad design is open for editing via this link, I think a small trapped button pusher is what I will do...rough CAD of this has just been added....

https://www.tinkercad.com/things/aCdffkB6ycg-sizzling-duup-krunk/edit?sharecode=bjAvZsCAanRYnLWeQIFOAiFzO0hGHiVB3LgwLgJzyv0=

**Comment by CRImier** [comment]
[Available for sale on Tindie](https://www.tindie.com/products/CRImier/sd-card-locker-make-true-read-only-sdmicrosd/) now! Finally got around to fixing and testing the 7 PCBs that I have, as well as making the cases.

![sd locker picture](https://cdn.hackaday.io/images/original//6315761557994267880.JPG)
